[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test"
cache_path = "cache_forge"
solc = "0.8.20"

# Compiler settings
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

# Remappings
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'forge-std/=node_modules/forge-std/src/'
]
